//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TbCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbCustomer()
        {
            this.TbSales = new HashSet<TbSales>();
        }
    
        public int CustomerId { get; set; }
        [Required(ErrorMessage ="Müþteri Adýný Giriniz")]
        public string CustomerName { get; set; }
        [Required(ErrorMessage ="Müþteri Soyadýnýz Giriniz")]
        public string CustomerLastName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbSales> TbSales { get; set; }
    }
}
