//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TbProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbProduct()
        {
            this.TbSales = new HashSet<TbSales>();
        }
    
        public int ProductId { get; set; }
        [Required(ErrorMessage ="Ürün Adýný Giriniz")]
        public string ProductName { get; set; }
        
        public Nullable<int> ProductCategory { get; set; }
        [Required(ErrorMessage ="Ürün Fiyatýný Giriniz")]
        public Nullable<decimal> Price { get; set; }
    
        public virtual TbCategory TbCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbSales> TbSales { get; set; }
    }
}
